name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ "8.1", "8.2", "8.3" ]
        laravel: [ "^10.0", "^11.0" ]
        dependency-version: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: "^10.0"
            testbench: "^8.0"
          - laravel: "^11.0"
            testbench: "^9.0"
        exclude:
          - php: "8.3"
            laravel: "^10.0"
          - php: "8.1"
            laravel: "^11.0"

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.30.2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: pcov

      - uses: actions/cache@v3.0.5
        name: Cache dependencies
        with:
          path: ~/.composer/cache/files
          key: composer-php-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.prefer }}-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction


      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Brew install tap
        run: brew install tursodatabase/tap/turso

      - name: Run worker server
        run: |
          turso dev --port 8081 &
          sleep 5

      - name: Run tests
        run: |
          vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - uses: codecov/codecov-action@v3.1.0
        with:
          fail_ci_if_error: false
